name: New feature
description: Suggest an enhancement or new feature  
title: "[V2]: <title>"  
labels: ["enhancement"]  
projects: ["helixbox/1"]  
assignees:  
  - windatang  
body:  
- type: textarea  
  attributes:  
    label: Describtion
  validations:  
    required: false  
